name: Quality checks

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring

      - name: Install Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Bootstraping .env
        run: cp .env.example .env

      - name: Code style
        run: composer style

      - name: Run tests
        run: composer test